// <auto-generated />
using System;
using Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240622110209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Abstractions.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Abstractions.LocalizableEntity", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("NameRu")
                        .HasColumnType("text");

                    b.Property<string>("NameUz")
                        .HasColumnType("text");

                    b.HasIndex("Name", "NameUz", "NameRu", "NameEn")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LocalizableEntity");
                });

            modelBuilder.Entity("Domain.Abstractions.PersonBase", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Middlename")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("PersonBase");
                });

            modelBuilder.Entity("Domain.Entities.UserEducation", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<Guid>("EducationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("EducationId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("UserEducation_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserEducation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bf11bb3-0aee-49c4-be76-6ae88c378c5f"),
                            IsDeleted = false,
                            EducationId = new Guid("8adfdfe0-54b2-4840-9d90-5ca527ca7512"),
                            From = new DateOnly(2020, 9, 4),
                            To = new DateOnly(2024, 6, 15),
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        },
                        new
                        {
                            Id = new Guid("5c1d4ef7-4023-49e3-b1e1-ebd7a1ec2b89"),
                            IsDeleted = false,
                            EducationId = new Guid("036ea1e2-9572-49df-9dd3-73eb175e99aa"),
                            From = new DateOnly(2022, 7, 1),
                            To = new DateOnly(2023, 4, 30),
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserExperience", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("From")
                        .HasColumnType("date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkTypeId")
                        .HasColumnType("uuid");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("From")
                                .HasColumnName("UserExperience_From");

                            t.Property("PositionId")
                                .HasColumnName("UserExperience_PositionId");

                            t.Property("To")
                                .HasColumnName("UserExperience_To");

                            t.Property("UserId")
                                .HasColumnName("UserExperience_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserExperience");
                });

            modelBuilder.Entity("Domain.Entities.UserLanguage", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("UserLanguage_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserLanguage");
                });

            modelBuilder.Entity("Domain.Entities.UserSkill", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<string>("PhotoName")
                        .HasColumnType("text");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PhotoName")
                                .HasColumnName("UserSkill_PhotoName");

                            t.Property("UserId")
                                .HasColumnName("UserSkill_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserSkill");
                });

            modelBuilder.Entity("Domain.Entities.UserSocialNetwork", b =>
                {
                    b.HasBaseType("Domain.Abstractions.BaseEntity");

                    b.Property<Guid>("SocialNetworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("SocialNetworkId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("UserId", "SocialNetworkId")
                        .IsUnique();

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Url")
                                .HasColumnName("UserSocialNetwork_Url");

                            t.Property("UserId")
                                .HasColumnName("UserSocialNetwork_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserSocialNetwork");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13224e19-0471-48e0-86ee-9368af808598"),
                            IsDeleted = false,
                            SocialNetworkId = new Guid("825c1d49-7e85-4370-9589-9e81c1e739f1"),
                            Url = "https://t.me/Sarvarbek_Abduqodirov",
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        },
                        new
                        {
                            Id = new Guid("cda4d3ab-03ed-40da-90ba-a05d472c1dc3"),
                            IsDeleted = false,
                            SocialNetworkId = new Guid("01753ef1-9be5-43f7-ba3a-fb822ad87982"),
                            Url = "https://www.linkedin.com/in/abduqodirov-sarvarbek/",
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        },
                        new
                        {
                            Id = new Guid("08c34f4e-df60-481f-839c-03229139481b"),
                            IsDeleted = false,
                            SocialNetworkId = new Guid("2af3c7b1-6d60-443d-8cbc-251a4beda498"),
                            Url = "https://github.com/AbduqodirovSarvar",
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        },
                        new
                        {
                            Id = new Guid("4a7ada3d-afe2-4fa5-81c1-cbb8e4657004"),
                            IsDeleted = false,
                            SocialNetworkId = new Guid("b6da8195-c7c7-470a-a7da-597e85aed801"),
                            Url = "https://gitlab.com/Abduqodirov_Sarvar",
                            UserId = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70")
                        });
                });

            modelBuilder.Entity("Domain.Abstractions.LocalizableWithDescriptionEntity", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("text");

                    b.HasIndex("Description", "DescriptionUz", "DescriptionRu", "DescriptionEn")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LocalizableWithDescriptionEntity");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid");

                    b.HasIndex("CountyId");

                    b.HasDiscriminator().HasValue("City");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dea64ab9-38ac-4946-8e57-59d20b3d9826"),
                            IsDeleted = false,
                            Name = "Tashkent",
                            NameEn = "Tashkent",
                            NameRu = "Ташкент",
                            NameUz = "Toshkent",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("7d87f413-efd4-4313-8f9a-0d65cd20eb9b"),
                            IsDeleted = false,
                            Name = "Namangan",
                            NameEn = "Namangan",
                            NameRu = "Наманган",
                            NameUz = "Namangan",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("23d01184-c074-48d3-ac29-1bf6bfebafab"),
                            IsDeleted = false,
                            Name = "Samarkand",
                            NameEn = "Samarkand",
                            NameRu = "Самарканд",
                            NameUz = "Samarqand",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("c111ddeb-f701-4a2e-862f-d1e918033997"),
                            IsDeleted = false,
                            Name = "Andijan",
                            NameEn = "Andijan",
                            NameRu = "Андижан",
                            NameUz = "Andijon",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("48485b98-97a4-4763-ab4e-45fa0916bb5d"),
                            IsDeleted = false,
                            Name = "Nukus",
                            NameEn = "Nukus",
                            NameRu = "Нукус",
                            NameUz = "Nukus",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("8644e508-27de-4862-81a8-a7f326077bed"),
                            IsDeleted = false,
                            Name = "Fergana",
                            NameEn = "Fergana",
                            NameRu = "Фергана",
                            NameUz = "Farg'ona",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("627e18e9-e089-436b-9b9c-605601e0cf27"),
                            IsDeleted = false,
                            Name = "Bukhara",
                            NameEn = "Bukhara",
                            NameRu = "Бухара",
                            NameUz = "Buxoro",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("c841ae8d-55da-4cf0-b977-6325db5cdbe0"),
                            IsDeleted = false,
                            Name = "Qarshi",
                            NameEn = "Qarshi",
                            NameRu = "Карши",
                            NameUz = "Qarshi",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("c990d2b3-8295-487d-bb55-ed4ae081be4d"),
                            IsDeleted = false,
                            Name = "Kokand",
                            NameEn = "Kokand",
                            NameRu = "Коканд",
                            NameUz = "Qo'qon",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("264d8795-b9f1-4a2c-abb9-5a58b2182156"),
                            IsDeleted = false,
                            Name = "Margilan",
                            NameEn = "Margilan",
                            NameRu = "Маргилан",
                            NameUz = "Marg'ilon",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("b7d6d47f-723c-4f41-b3b5-9e80d2b2ec4a"),
                            IsDeleted = false,
                            Name = "Termez",
                            NameEn = "Termez",
                            NameRu = "Термез",
                            NameUz = "Termiz",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("aa59dfa5-3c04-48cc-8fc1-585036d8193e"),
                            IsDeleted = false,
                            Name = "Jizzakh",
                            NameEn = "Jizzakh",
                            NameRu = "Джизак",
                            NameUz = "Jizzax",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("65dcb207-34bf-41d9-986d-f0a3ff8cf38e"),
                            IsDeleted = false,
                            Name = "Angren",
                            NameEn = "Angren",
                            NameRu = "Ангрен",
                            NameUz = "Angren",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("91078b75-15d4-4efb-b75b-e62f02f8fc6b"),
                            IsDeleted = false,
                            Name = "Chirchiq",
                            NameEn = "Chirchiq",
                            NameRu = "Чирчик",
                            NameUz = "Chirchiq",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("2efbb53e-9f47-4a91-bda5-d9a1c9ec2a0d"),
                            IsDeleted = false,
                            Name = "Navoiy",
                            NameEn = "Navoiy",
                            NameRu = "Навоий",
                            NameUz = "Navoiy",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("917331bd-0a85-4db7-aed2-4b5f1782589b"),
                            IsDeleted = false,
                            Name = "Urgench",
                            NameEn = "Urgench",
                            NameRu = "Ургенч",
                            NameUz = "Urganch",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("fd24566b-b37b-4f0e-8285-4ebe22fcd9a3"),
                            IsDeleted = false,
                            Name = "Shahrisabz",
                            NameEn = "Shahrisabz",
                            NameRu = "Шахрисабз",
                            NameUz = "Shahrisabz",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("186a5475-1344-4697-898e-72bf64bc7bcc"),
                            IsDeleted = false,
                            Name = "Olmaliq",
                            NameEn = "Olmaliq",
                            NameRu = "Олмалиқ",
                            NameUz = "Olmaliq",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("baa8ab48-1134-42a3-a8f7-cdf6142c8cd4"),
                            IsDeleted = false,
                            Name = "Bekobod",
                            NameEn = "Bekobod",
                            NameRu = "Бекобод",
                            NameUz = "Bekobod",
                            CountyId = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2")
                        },
                        new
                        {
                            Id = new Guid("c4c0486e-1f36-4e7a-a6c5-b774b366ba4f"),
                            IsDeleted = false,
                            Name = "Almaty",
                            NameEn = "Almaty",
                            NameRu = "Алматы",
                            NameUz = "Almaty",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("6c35504e-8c77-41ef-b486-098861d11ca5"),
                            IsDeleted = false,
                            Name = "Nur-Sultan",
                            NameEn = "Nur-Sultan",
                            NameRu = "Нур-Султан",
                            NameUz = "Nur-Sultan",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("7ac07dbb-f3ac-4431-a566-38962e18325d"),
                            IsDeleted = false,
                            Name = "Shymkent",
                            NameEn = "Shymkent",
                            NameRu = "Шымкент",
                            NameUz = "Shymkent",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("e845d41c-d99a-4e30-a65f-a92f44cb105d"),
                            IsDeleted = false,
                            Name = "Karaganda",
                            NameEn = "Karaganda",
                            NameRu = "Караганда",
                            NameUz = "Karaganda",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("843bb202-b89f-4f14-87c5-00bfcf8e5971"),
                            IsDeleted = false,
                            Name = "Aktobe",
                            NameEn = "Aktobe",
                            NameRu = "Актобе",
                            NameUz = "Aktobe",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("4d7d39d7-084d-4d77-81cd-d8ae39ef3b46"),
                            IsDeleted = false,
                            Name = "Taraz",
                            NameEn = "Taraz",
                            NameRu = "Тараз",
                            NameUz = "Taraz",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("2720d806-9e3f-4ab6-ac0f-f98627cd0f10"),
                            IsDeleted = false,
                            Name = "Pavlodar",
                            NameEn = "Pavlodar",
                            NameRu = "Павлодар",
                            NameUz = "Pavlodar",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("647e43a0-531e-4e3d-a711-e76232e880b5"),
                            IsDeleted = false,
                            Name = "Ust-Kamenogorsk",
                            NameEn = "Ust-Kamenogorsk",
                            NameRu = "Усть-Каменогорск",
                            NameUz = "Ust-Kamenogorsk",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("79aaee46-2bf3-4645-905a-5743415e410f"),
                            IsDeleted = false,
                            Name = "Semey",
                            NameEn = "Semey",
                            NameRu = "Семей",
                            NameUz = "Semey",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("2ed77a79-0fbc-43d6-bdc8-e847e6938686"),
                            IsDeleted = false,
                            Name = "Kostanay",
                            NameEn = "Kostanay",
                            NameRu = "Костанай",
                            NameUz = "Kostanay",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("9baecd59-6820-4bbb-8fef-47deb23b437c"),
                            IsDeleted = false,
                            Name = "Petropavl",
                            NameEn = "Petropavl",
                            NameRu = "Петропавловск",
                            NameUz = "Petropavl",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("9805cd14-2a76-44e3-b603-438a791a1588"),
                            IsDeleted = false,
                            Name = "Oral",
                            NameEn = "Oral",
                            NameRu = "Уральск",
                            NameUz = "Oral",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("5fb5d34a-8c8f-40c9-858c-df62c0e90944"),
                            IsDeleted = false,
                            Name = "Kyzylorda",
                            NameEn = "Kyzylorda",
                            NameRu = "Кызылорда",
                            NameUz = "Kyzylorda",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("089e8e8a-a40f-4e36-894b-6c0e62796f91"),
                            IsDeleted = false,
                            Name = "Atyrau",
                            NameEn = "Atyrau",
                            NameRu = "Атырау",
                            NameUz = "Atyrau",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("05797799-d737-4b95-a027-05a64326d9ee"),
                            IsDeleted = false,
                            Name = "Temirtau",
                            NameEn = "Temirtau",
                            NameRu = "Темиртау",
                            NameUz = "Temirtau",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("5653c687-5109-4499-8a5b-a9e2a20b7dcd"),
                            IsDeleted = false,
                            Name = "Aktau",
                            NameEn = "Aktau",
                            NameRu = "Актау",
                            NameUz = "Aktau",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("871b5b9a-f56c-4b7a-9812-657e9b1ea291"),
                            IsDeleted = false,
                            Name = "Balqash",
                            NameEn = "Balqash",
                            NameRu = "Балхаш",
                            NameUz = "Balqash",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("87dc6e62-ce5b-49b0-91c9-23c9d06e2948"),
                            IsDeleted = false,
                            Name = "Kokshetau",
                            NameEn = "Kokshetau",
                            NameRu = "Кокшетау",
                            NameUz = "Kokshetau",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("bfd49bf2-01f2-4d3c-acb5-b2aac2e8b799"),
                            IsDeleted = false,
                            Name = "Taldykorgan",
                            NameEn = "Taldykorgan",
                            NameRu = "Талдыкорган",
                            NameUz = "Taldykorgan",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        },
                        new
                        {
                            Id = new Guid("b90c3bde-7656-4784-8d36-a8e6c29304f5"),
                            IsDeleted = false,
                            Name = "Kyzyl-Orda",
                            NameEn = "Kyzyl-Orda",
                            NameRu = "Кызылорда",
                            NameUz = "Kyzyl-Orda",
                            CountyId = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.HasDiscriminator().HasValue("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("774cdeef-2ec6-452b-8b77-786d123383a2"),
                            IsDeleted = false,
                            Name = "Uzbekistan",
                            NameEn = "Uzbekistan",
                            NameRu = "Узбекистан",
                            NameUz = "O'zbekiston"
                        },
                        new
                        {
                            Id = new Guid("47d43abb-bc32-4d71-8b3b-dc2e77f4c987"),
                            IsDeleted = false,
                            Name = "Kazakhstan",
                            NameEn = "Kazakhstan",
                            NameRu = "Казахстан",
                            NameUz = "Qozog'iston"
                        },
                        new
                        {
                            Id = new Guid("56064f79-822e-4049-a520-0fbe7f735677"),
                            IsDeleted = false,
                            Name = "Turkmenistan",
                            NameEn = "Turkmenistan",
                            NameRu = "Туркменистан",
                            NameUz = "Turkmaniston"
                        },
                        new
                        {
                            Id = new Guid("fe637e68-b9ae-49b6-b162-83756d43ff7b"),
                            IsDeleted = false,
                            Name = "Kyrgyzstan",
                            NameEn = "Kyrgyzstan",
                            NameRu = "Киргизия",
                            NameUz = "Qirg'iziston"
                        },
                        new
                        {
                            Id = new Guid("fb75ee14-c75e-48af-a099-56c9c41778d2"),
                            IsDeleted = false,
                            Name = "Tajikistan",
                            NameEn = "Tajikistan",
                            NameRu = "Таджикистан",
                            NameUz = "Tojikiston"
                        },
                        new
                        {
                            Id = new Guid("1434e50f-5652-4798-840e-4d540379073e"),
                            IsDeleted = false,
                            Name = "China",
                            NameEn = "China",
                            NameRu = "Китай",
                            NameUz = "Xitoy"
                        },
                        new
                        {
                            Id = new Guid("66fbc0d6-d5de-413d-9a65-0f14d0cd728c"),
                            IsDeleted = false,
                            Name = "India",
                            NameEn = "India",
                            NameRu = "Индия",
                            NameUz = "Hindiston"
                        },
                        new
                        {
                            Id = new Guid("fd9fe4b7-7c51-405d-bd5d-48d6474706ae"),
                            IsDeleted = false,
                            Name = "Japan",
                            NameEn = "Japan",
                            NameRu = "Япония",
                            NameUz = "Yaponiya"
                        },
                        new
                        {
                            Id = new Guid("be2d0cc2-79a5-403b-9341-d625e4478bce"),
                            IsDeleted = false,
                            Name = "South Korea",
                            NameEn = "South Korea",
                            NameRu = "Южная Корея",
                            NameUz = "Janubiy Koreya"
                        },
                        new
                        {
                            Id = new Guid("02833fc8-089a-4d98-bde5-99a6b06498c9"),
                            IsDeleted = false,
                            Name = "Vietnam",
                            NameEn = "Vietnam",
                            NameRu = "Вьетнам",
                            NameUz = "Vyetnam"
                        },
                        new
                        {
                            Id = new Guid("1237d6d9-5c71-4810-bdb9-d886a6a2ffd7"),
                            IsDeleted = false,
                            Name = "Indonesia",
                            NameEn = "Indonesia",
                            NameRu = "Индонезия",
                            NameUz = "Indoneziya"
                        },
                        new
                        {
                            Id = new Guid("047611bf-1804-4c4e-8110-47074b55849c"),
                            IsDeleted = false,
                            Name = "Turkey",
                            NameEn = "Turkey",
                            NameRu = "Турция",
                            NameUz = "Turkiya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.HasDiscriminator().HasValue("Language");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ebe6791-072a-49bf-9c0e-32ea1cc7786a"),
                            IsDeleted = false,
                            Name = "Uzbek",
                            NameEn = "Uzbek",
                            NameRu = "Узбекский",
                            NameUz = "O'zbekcha"
                        },
                        new
                        {
                            Id = new Guid("142d9be6-049a-4335-8d87-f470edde2c3c"),
                            IsDeleted = false,
                            Name = "English",
                            NameEn = "English",
                            NameRu = "Английский",
                            NameUz = "Inglizcha"
                        },
                        new
                        {
                            Id = new Guid("22185df5-b9ea-4030-8cd6-627f873f01fe"),
                            IsDeleted = false,
                            Name = "Russian",
                            NameEn = "Russian",
                            NameRu = "Русский",
                            NameUz = "Ruscha"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SocialNetwork", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.HasDiscriminator().HasValue("SocialNetwork");

                    b.HasData(
                        new
                        {
                            Id = new Guid("825c1d49-7e85-4370-9589-9e81c1e739f1"),
                            IsDeleted = false,
                            Name = "Telegram",
                            NameEn = "Telegram",
                            NameRu = "Телеграм",
                            NameUz = "Telegram"
                        },
                        new
                        {
                            Id = new Guid("01753ef1-9be5-43f7-ba3a-fb822ad87982"),
                            IsDeleted = false,
                            Name = "LinkedIn",
                            NameEn = "LinkedIn",
                            NameRu = "LinkedIn",
                            NameUz = "LinkedIn"
                        },
                        new
                        {
                            Id = new Guid("2af3c7b1-6d60-443d-8cbc-251a4beda498"),
                            IsDeleted = false,
                            Name = "GitHub",
                            NameEn = "GitHub",
                            NameRu = "GitHub",
                            NameUz = "GitHub"
                        },
                        new
                        {
                            Id = new Guid("b6da8195-c7c7-470a-a7da-597e85aed801"),
                            IsDeleted = false,
                            Name = "GitLab",
                            NameEn = "GitLab",
                            NameRu = "GitLab",
                            NameUz = "GitLab"
                        },
                        new
                        {
                            Id = new Guid("cb8453fa-cf95-4b29-abfe-ca460118b052"),
                            IsDeleted = false,
                            Name = "Twitter",
                            NameEn = "Twitter",
                            NameRu = "Твиттер",
                            NameUz = "Twitter"
                        },
                        new
                        {
                            Id = new Guid("71fe90b6-15ff-4170-bbbe-b85445f21ab8"),
                            IsDeleted = false,
                            Name = "Instagram",
                            NameEn = "Instagram",
                            NameRu = "Инстаграм",
                            NameUz = "Instagram"
                        },
                        new
                        {
                            Id = new Guid("131db6e1-cec9-4e2a-a174-5d6407e11309"),
                            IsDeleted = false,
                            Name = "Thread",
                            NameEn = "Thread",
                            NameRu = "Thread",
                            NameUz = "Thread"
                        },
                        new
                        {
                            Id = new Guid("aa8ad639-fdcb-4f36-b815-dbf633e133b7"),
                            IsDeleted = false,
                            Name = "WhatsUp",
                            NameEn = "WhatsApp",
                            NameRu = "WhatsApp",
                            NameUz = "WhatsUp"
                        },
                        new
                        {
                            Id = new Guid("f1aaab0e-fd3a-4b93-bf06-2a926dc6e940"),
                            IsDeleted = false,
                            Name = "Skype",
                            NameEn = "Skype",
                            NameRu = "Skype",
                            NameUz = "Skype"
                        },
                        new
                        {
                            Id = new Guid("1aaf684b-5535-486b-b21d-bf252bdb18ab"),
                            IsDeleted = false,
                            Name = "Imo",
                            NameEn = "Imo",
                            NameRu = "Imo",
                            NameUz = "Imo"
                        },
                        new
                        {
                            Id = new Guid("3680e7df-36db-48e1-a3ae-7b208e40da4c"),
                            IsDeleted = false,
                            Name = "Zoom",
                            NameEn = "Zoom",
                            NameRu = "Zoom",
                            NameUz = "Zoom"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UITheme", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableEntity");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("UITheme");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasBaseType("Domain.Abstractions.PersonBase");

                    b.Property<string>("AboutMe")
                        .HasColumnType("text");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoName")
                        .HasColumnType("text");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResumeName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UIThemeId")
                        .HasColumnType("uuid");

                    b.HasIndex("CityId");

                    b.HasIndex("PositionId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CityId")
                                .HasColumnName("User_CityId");
                        });

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55ae23c0-2852-460f-b918-eb40a6687c70"),
                            IsDeleted = false,
                            Birthday = new DateOnly(2002, 3, 16),
                            Email = "abduqodirovsarvar.2002@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Sarvarbek",
                            Gender = 1,
                            Lastname = "Abduqodirov",
                            Middlename = "Xasan o'g'li",
                            Phone = "+998932340316",
                            AboutMe = "I am a junior Software Engineer. Skilled and curious young software engineer with 1.5 years of experience in building robust systems using .NET Core on backend and React, Typescript on frontend. Wants to design solid architecture and clean code. Good understanding of object oriented programming and fast learning.",
                            CityId = new Guid("dea64ab9-38ac-4946-8e57-59d20b3d9826"),
                            PasswordHash = "hnCh7L+J7zhoRIEK6JSlWxRyPG5tWobtZxAFZO/5RwwQ6YK9oKQIm17KFOdH7U1nBt9QXjz7kRWFTOIAnqmnJg==",
                            PositionId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.HasIndex("CityId");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5f1064e-a1e3-47a8-99c5-eaad6ccc14e4"),
                            IsDeleted = false,
                            Name = "ITransition",
                            NameEn = "ITransition",
                            NameRu = "ITransition",
                            NameUz = "ITransition",
                            Description = "ITransition is a global provider of software development, QA, and consulting services with a focus on advanced technologies.",
                            DescriptionEn = "ITransition is a global provider of software development, QA, and consulting services with a focus on advanced technologies.",
                            DescriptionRu = "ITransition — международный поставщик услуг по разработке программного обеспечения, QA и консалтинга с акцентом на передовые технологии.",
                            DescriptionUz = "ITransition yuqori texnologiyalar ustida qurilgan dasturlar va ilovalarni rivojlantirish, QA va konsalting xizmatlari taqdim etuvchi global kompaniyadir.",
                            CityId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("fe5e6043-644b-424c-91b7-036e420e51cf"),
                            IsDeleted = false,
                            Name = "BePro-DEVHUB",
                            NameEn = "BePro-DEVHUB",
                            NameRu = "BePro-DEVHUB",
                            NameUz = "BePro-DEVHUB",
                            Description = "BePro-DEVHUB is a software development and IT consulting company specializing in web and mobile app development.",
                            DescriptionEn = "BePro-DEVHUB is a software development and IT consulting company specializing in web and mobile app development.",
                            DescriptionRu = "BePro-DEVHUB — это компания по разработке программного обеспечения и IT-консалтингу, специализирующаяся на разработке веб и мобильных приложений.",
                            DescriptionUz = "BePro-DEVHUB veb va mobil ilovalar dasturlashida ihtisoslashgan dasturiy ta'minot va IT konsalting kompaniyasidir.",
                            CityId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7d7e10a3-6711-440b-8cae-f42804eabcb7"),
                            IsDeleted = false,
                            Name = "EPAM",
                            NameEn = "EPAM",
                            NameRu = "EPAM",
                            NameUz = "EPAM",
                            Description = "EPAM Systems is a leading global provider of digital platform engineering and software development services.",
                            DescriptionEn = "EPAM Systems is a leading global provider of digital platform engineering and software development services.",
                            DescriptionRu = "EPAM Systems — ведущий мировой поставщик цифровой платформенной инженерии и разработки программного обеспечения.",
                            DescriptionUz = "EPAM Systems dunyoning eng yuqori darajadagi raqamli platforma injenerlik va dasturlash xizmatlari taqdim etuvchi global tajribali kompaniyadir.",
                            CityId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ee494401-9095-46ea-93c6-f0b67d3a7cd3"),
                            IsDeleted = false,
                            Name = "EXADEL",
                            NameEn = "EXADEL",
                            NameRu = "EXADEL",
                            NameUz = "EXADEL",
                            Description = "Exadel is a global software engineering company that provides full-cycle software development, QA, and testing services.",
                            DescriptionEn = "Exadel is a global software engineering company that provides full-cycle software development, QA, and testing services.",
                            DescriptionRu = "Exadel — это международная компания по разработке программного обеспечения, предоставляющая полный цикл разработки ПО, QA и тестирования.",
                            DescriptionUz = "Exadel global dasturiy injinerlik kompaniyasi, to'liq tsikl dasturiy ta'minot, QA va sinov xizmatlari taqdim etadi.",
                            CityId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Education", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.HasIndex("CityId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CityId")
                                .HasColumnName("Education_CityId");
                        });

                    b.HasDiscriminator().HasValue("Education");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8adfdfe0-54b2-4840-9d90-5ca527ca7512"),
                            IsDeleted = false,
                            Name = "Tashkent University of Information Technologies",
                            NameEn = "Tashkent University of Information Technologies",
                            NameRu = "Ташкентский университет информационных технологий",
                            NameUz = "Toshkent axborot texnologiyalari universiteti",
                            Description = "Tashkent University of Information Technologies (TUIT) is a leading educational institution in Uzbekistan specializing in IT and related fields.",
                            DescriptionEn = "Tashkent University of Information Technologies (TUIT) is a leading educational institution in Uzbekistan specializing in IT and related fields.",
                            DescriptionRu = "Ташкентский университет информационных технологий (ТАТУ) является ведущим образовательным учреждением в Узбекистане, специализирующимся в области ИТ и смежных направлений.",
                            DescriptionUz = "Toshkent axborot texnologiyalari universiteti (TATU) O'zbekistonda IT va undan qo'shimcha sohalar bo'yicha yetakchi ta'lim muassasasi hisoblanadi.",
                            CityId = new Guid("dea64ab9-38ac-4946-8e57-59d20b3d9826")
                        },
                        new
                        {
                            Id = new Guid("036ea1e2-9572-49df-9dd3-73eb175e99aa"),
                            IsDeleted = false,
                            Name = "Najot Ta'lim IT Academy",
                            NameEn = "Najot Ta'lim IT Academy",
                            NameRu = "IT-академия «Наджот Таълим»",
                            NameUz = "Najot Ta'lim IT Akademiyasi",
                            Description = "Najot Ta'lim IT Academy is an educational institution in Uzbekistan that specializes in IT education and training.",
                            DescriptionEn = "Najot Ta'lim IT Academy is an educational institution in Uzbekistan that specializes in IT education and training.",
                            DescriptionRu = "IT-академия «Наджот Таълим» - образовательное учреждение в Узбекистане, специализирующееся на образовании и тренинге в области информационных технологий.",
                            DescriptionUz = "Najot Ta'lim IT Akademiyasi O'zbekistonda IT ta'limi va tayyorlash sohasiga ixtisoslashgan ta'lim muassasasi.",
                            CityId = new Guid("dea64ab9-38ac-4946-8e57-59d20b3d9826")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Level", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.HasDiscriminator().HasValue("Level");

                    b.HasData(
                        new
                        {
                            Id = new Guid("706a544c-131e-44e3-9509-b5c9e34b4b19"),
                            IsDeleted = false,
                            Name = "Beginner",
                            NameEn = "Beginner",
                            NameRu = "Начинающий",
                            NameUz = "Boshlang'ich",
                            Description = "Basic understanding of the language with limited vocabulary and simple grammar.",
                            DescriptionEn = "Basic understanding of the language with limited vocabulary and simple grammar.",
                            DescriptionRu = "Основное понимание языка с ограниченным словарным запасом и простой грамматикой.",
                            DescriptionUz = "O'z tilini boshlang'ich darajada o'rganish, chegaraviy so'zlashish va oddiy grammatikaga ega bo'lish."
                        },
                        new
                        {
                            Id = new Guid("8e0f1d00-3848-49a4-8f7a-509203e94013"),
                            IsDeleted = false,
                            Name = "Elementary",
                            NameEn = "Elementary",
                            NameRu = "Начальный",
                            NameUz = "O'rtacha",
                            Description = "Basic comprehension of everyday expressions and simple phrases. Can introduce yourself and ask basic questions about personal information.",
                            DescriptionEn = "Basic comprehension of everyday expressions and simple phrases. Can introduce yourself and ask basic questions about personal information.",
                            DescriptionRu = "Основное понимание повседневных выражений и простых фраз. Можете представиться и задать базовые вопросы о личной информации.",
                            DescriptionUz = "Kundalik ifodalar va oddiy iboralar o'rnating. O'zingizni tanishtirishingiz va shaxsiy ma'lumotlaringiz haqida oddiy savollar berishingiz mumkin."
                        },
                        new
                        {
                            Id = new Guid("2f31407e-7a81-4ec6-9993-db2ba1524435"),
                            IsDeleted = false,
                            Name = "Intermediate",
                            NameEn = "Intermediate",
                            NameRu = "Средний",
                            NameUz = "O'rta",
                            Description = "Can understand the main points of clear standard input on familiar matters. Can produce simple connected text on topics that are familiar or of personal interest.",
                            DescriptionEn = "Can understand the main points of clear standard input on familiar matters. Can produce simple connected text on topics that are familiar or of personal interest.",
                            DescriptionRu = "Можете понять основные моменты понятных стандартных вводов по знакомым вопросам. Можете составить простой связанный текст по темам, которые вам знакомы или интересны лично.",
                            DescriptionUz = "Odatiy masalalar haqida bayonotdan foydalanib, asosiy nuqtalarni tushunish mumkin. Odatiy yoki shaxsiy qiziq mavzularida bog'liq oddiy bog'lanishgan matnlarni yaratish mumkin."
                        },
                        new
                        {
                            Id = new Guid("371598e2-1296-46ea-af9a-dd94de551d35"),
                            IsDeleted = false,
                            Name = "Upper-Intermediate",
                            NameEn = "Upper-Intermediate",
                            NameRu = "Выше среднего",
                            NameUz = "Yuqori o'rta",
                            Description = "Can understand the main ideas of complex text on both concrete and abstract topics. Can interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.",
                            DescriptionEn = "Can understand the main ideas of complex text on both concrete and abstract topics. Can interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.",
                            DescriptionRu = "Можете понять основные идеи сложного текста по конкретным и абстрактным темам. Можете взаимодействовать с определенной степенью беглости и спонтанности, что делает регулярное общение с носителями языка возможным без напряжения для обеих сторон.",
                            DescriptionUz = "Aniq yoki abstrakt mavzularda kompleks matnlarning asosiy o'zini tushunish mumkin. Huddi shaxsiyatli so'zlashish va spantane so'zlashish darajasida soddalik bilan amalga oshirish mumkin, bu esa har ikki taraf uchun ham zo'ravon bo'lishsiz mumkin."
                        },
                        new
                        {
                            Id = new Guid("4f5fd2f2-7057-4c20-ae4c-a4173cbe1936"),
                            IsDeleted = false,
                            Name = "Advanced",
                            NameEn = "Advanced",
                            NameRu = "Продвинутый",
                            NameUz = "Yuqori",
                            Description = "Can understand a wide range of demanding, longer texts, and recognize implicit meaning. Can express ideas fluently and spontaneously without much obvious searching for expressions.",
                            DescriptionEn = "Can understand a wide range of demanding, longer texts, and recognize implicit meaning. Can express ideas fluently and spontaneously without much obvious searching for expressions.",
                            DescriptionRu = "Можете понять широкий круг требовательных, длинных текстов и распознать неявное значение. Можете выражать идеи бегло и спонтанно без явного поиска выражений.",
                            DescriptionUz = "Murakkab va uzun matnlarning keng tarqalgan qatorini tushunish va zimmasiz manoni aniqlash mumkin. Ideyalarni boshqarish uchun shifobaxsh va spantane so'zlashish, tushunarli talab qilmaydi."
                        },
                        new
                        {
                            Id = new Guid("edf5b31d-a35b-4e88-a739-5e54320c2303"),
                            IsDeleted = false,
                            Name = "Native",
                            NameEn = "Native",
                            NameRu = "Родной",
                            NameUz = "Ona tili",
                            Description = "Has a complete command of the language, including idiomatic expressions and colloquialisms. Speaks the language fluently and accurately.",
                            DescriptionEn = "Has a complete command of the language, including idiomatic expressions and colloquialisms. Speaks the language fluently and accurately.",
                            DescriptionRu = "Имеет полное владение языком, включая идиоматические выражения и разговорную речь. Говорит на языке бегло и точно.",
                            DescriptionUz = "Istiqlolik va umumiy gaplashishdagi ona tili hisoblanadi, so'zlashishga ishonch keltiradi."
                        });
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.HasDiscriminator().HasValue("Position");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13384688-5d0e-433f-a1a3-0c22dbd77726"),
                            IsDeleted = false,
                            Name = "Backend Developer",
                            NameEn = "Backend Developer",
                            NameRu = "Бэкенд разработчик",
                            NameUz = "Backend dasturchi",
                            Description = "Develops and maintains the server-side logic of web applications.",
                            DescriptionEn = "Develops and maintains the server-side logic of web applications.",
                            DescriptionRu = "Разрабатывает и поддерживает серверную логику веб-приложений.",
                            DescriptionUz = "Veb ilovalar server tomonidagi logikasini rivojlantirish va saqlash."
                        },
                        new
                        {
                            Id = new Guid("d6fe323f-1349-413d-9b97-999df77d70c3"),
                            IsDeleted = false,
                            Name = "Frontend Developer",
                            NameEn = "Frontend Developer",
                            NameRu = "Фронтенд разработчик",
                            NameUz = "Frontend dasturchi",
                            Description = "Builds and maintains the client-side of web applications.",
                            DescriptionEn = "Builds and maintains the client-side of web applications.",
                            DescriptionRu = "Строит и поддерживает клиентскую часть веб-приложений.",
                            DescriptionUz = "Veb ilovalarning mijoz tomonini yaratish va saqlash."
                        },
                        new
                        {
                            Id = new Guid("c35e35bd-d254-43e3-985a-81caa58da01a"),
                            IsDeleted = false,
                            Name = "System Administrator",
                            NameEn = "System Administrator",
                            NameRu = "Системный администратор",
                            NameUz = "Tizim administratori",
                            Description = "Responsible for maintaining and managing computer systems and networks within an organization.",
                            DescriptionEn = "Responsible for maintaining and managing computer systems and networks within an organization.",
                            DescriptionRu = "Ответственен за поддержание и управление компьютерными системами и сетями в организации.",
                            DescriptionUz = "Tashkilot ichidagi kompyuter tizimlari va tarmoqlarni saqlash va boshqarishdan mas'ul."
                        },
                        new
                        {
                            Id = new Guid("6ba06e7d-2f65-4aa6-9d6a-847b272df340"),
                            IsDeleted = false,
                            Name = "Network Engineer",
                            NameEn = "Network Engineer",
                            NameRu = "Сетевой инженер",
                            NameUz = "Tarmoq muhandisi",
                            Description = "Designs, implements, and manages data communication networks such as LANs and WANs.",
                            DescriptionEn = "Designs, implements, and manages data communication networks such as LANs and WANs.",
                            DescriptionRu = "Проектирует, внедряет и управляет сетями передачи данных, такими как LAN и WAN.",
                            DescriptionUz = "Mahalliy tarmoqlar (LAN) va keng sahalar (WAN) kabi ma'lumotlar almashish tarmoqlarini dizayn qilish, amalga oshirish va boshqarish."
                        },
                        new
                        {
                            Id = new Guid("3016022d-c3a8-462f-8361-44254450d058"),
                            IsDeleted = false,
                            Name = "IT Security Analyst",
                            NameEn = "IT Security Analyst",
                            NameRu = "Аналитик информационной безопасности",
                            NameUz = "IT Xavfsizlik tahliliy",
                            Description = "Monitors and protects an organization's computer systems and networks from cyber threats and attacks.",
                            DescriptionEn = "Monitors and protects an organization's computer systems and networks from cyber threats and attacks.",
                            DescriptionRu = "Мониторит и защищает компьютерные системы и сети организации от киберугроз и атак.",
                            DescriptionUz = "Tashkilotning kompyuter tizimlarini va tarmoqlarini onlayn xavf va hujumlaridan himoya qilish va nazorat qilish."
                        },
                        new
                        {
                            Id = new Guid("5a7ceb84-e379-4c93-9f79-e9524a474078"),
                            IsDeleted = false,
                            Name = "Database Administrator",
                            NameEn = "Database Administrator",
                            NameRu = "Администратор баз данных",
                            NameUz = "Ma'lumotlar bazasi administratori",
                            Description = "Manages and maintains an organization's database systems, ensuring data security, integrity, and availability.",
                            DescriptionEn = "Manages and maintains an organization's database systems, ensuring data security, integrity, and availability.",
                            DescriptionRu = "Управляет и поддерживает базы данных организации, обеспечивая безопасность, целостность и доступность данных.",
                            DescriptionUz = "Tashkilotning ma'lumotlar bazasini boshqarish va saqlash, ma'lumotlarni xavfsizligini, integritetini va mavjudligini ta'minlashdan mas'ul."
                        },
                        new
                        {
                            Id = new Guid("8ac56ceb-327c-4aac-89b7-3d9f49664578"),
                            IsDeleted = false,
                            Name = "IT Support Specialist",
                            NameEn = "IT Support Specialist",
                            NameRu = "Специалист по поддержке IT",
                            NameUz = "IT qo'llab-quvvat mutaxassis",
                            Description = "Provides technical support and troubleshooting for IT systems and end-users within an organization.",
                            DescriptionEn = "Provides technical support and troubleshooting for IT systems and end-users within an organization.",
                            DescriptionRu = "Обеспечивает техническую поддержку и устранение неполадок для IT систем и конечных пользователей в организации.",
                            DescriptionUz = "Tashkilot ichidagi IT tizimlari va foydalanuvchilar uchun texnik yordam va muammolar hal qilishni ta'minlash."
                        },
                        new
                        {
                            Id = new Guid("588c3b5e-5d09-49f2-bc4f-7f62dd9229dd"),
                            IsDeleted = false,
                            Name = "IT Project Manager",
                            NameEn = "IT Project Manager",
                            NameRu = "Менеджер IT проектов",
                            NameUz = "IT loyihalash boshqaruvi",
                            Description = "Plans, organizes, and oversees IT projects, ensuring they are completed on time, within budget, and meet organizational requirements.",
                            DescriptionEn = "Plans, organizes, and oversees IT projects, ensuring they are completed on time, within budget, and meet organizational requirements.",
                            DescriptionRu = "Планирует, организует и контролирует IT проекты, обеспечивая их выполнение в срок, в рамках бюджета и в соответствии с требованиями организации.",
                            DescriptionUz = "IT loyihalarini rejalashtirish, tashkil etish va boshqarish vaqti, byudjeti va tashkilot talablari bilan mos keladiganligini ta'minlash."
                        },
                        new
                        {
                            Id = new Guid("d7e8c774-3a60-4c5b-b41a-21a887766461"),
                            IsDeleted = false,
                            Name = "DevOps Engineer",
                            NameEn = "DevOps Engineer",
                            NameRu = "Инженер DevOps",
                            NameUz = "DevOps muhandisi",
                            Description = "Combines software development (Dev) and IT operations (Ops), ensuring continuous integration and delivery of software.",
                            DescriptionEn = "Combines software development (Dev) and IT operations (Ops), ensuring continuous integration and delivery of software.",
                            DescriptionRu = "Комбинирует разработку программного обеспечения (Dev) и операции IT (Ops), обеспечивая непрерывную интеграцию и доставку программного обеспечения.",
                            DescriptionUz = "Dastur ishlab chiqarish (Dev) va IT operatsiyalari (Ops)ni birlashtirib, dasturiy ta'minotlarni doimiy integratsiyasi va taqdimoti ta'minlash."
                        },
                        new
                        {
                            Id = new Guid("e826eb35-eeac-40b2-ab1f-4a42fe0026ac"),
                            IsDeleted = false,
                            Name = "Data Scientist",
                            NameEn = "Data Scientist",
                            NameRu = "Специалист по анализу данных",
                            NameUz = "Ma'lumot olimi",
                            Description = "Analyzes complex data sets to help organizations make informed decisions.",
                            DescriptionEn = "Analyzes complex data sets to help organizations make informed decisions.",
                            DescriptionRu = "Анализирует сложные наборы данных, чтобы помочь организациям принимать обоснованные решения.",
                            DescriptionUz = "Tashkilotlarga ma'lumotlardan foydalanishda yordam berish uchun murakkab ma'lumot to'plamlarini tahlil qiladi."
                        },
                        new
                        {
                            Id = new Guid("e071de89-7cd4-4ac9-9173-62dfd6229536"),
                            IsDeleted = false,
                            Name = "UX/UI Designer",
                            NameEn = "UX/UI Designer",
                            NameRu = "Дизайнер UX/UI",
                            NameUz = "UX/UI dizayneri",
                            Description = "Designs user experiences and user interfaces for digital products to enhance user satisfaction.",
                            DescriptionEn = "Designs user experiences and user interfaces for digital products to enhance user satisfaction.",
                            DescriptionRu = "Проектирует пользовательские интерфейсы и интерфейсы пользователя для цифровых продуктов для улучшения удовлетворенности пользователя.",
                            DescriptionUz = "Foydalanuvchi tajribalarini va raqamli mahsulotlar uchun foydalanuvchi interfeyslarini dizayn qilish, foydalanuvchining qoniqishini oshirish."
                        });
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.Property<Guid?>("UserProjectId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserProjectId");

                    b.HasDiscriminator().HasValue("Skill");
                });

            modelBuilder.Entity("Domain.Entities.UserCertificate", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.Property<string>("CertificateFileName")
                        .HasColumnType("text");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Credential")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Issued")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("UserCertificate");
                });

            modelBuilder.Entity("Domain.Entities.UserProject", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.Property<string>("PhotoName")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("UrlSrc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PhotoName")
                                .HasColumnName("UserProject_PhotoName");

                            t.Property("UserId")
                                .HasColumnName("UserProject_UserId");
                        });

                    b.HasDiscriminator().HasValue("UserProject");
                });

            modelBuilder.Entity("Domain.Entities.WorkType", b =>
                {
                    b.HasBaseType("Domain.Abstractions.LocalizableWithDescriptionEntity");

                    b.HasDiscriminator().HasValue("WorkType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52f59e3e-3767-45d7-b385-e267f6c4a55b"),
                            IsDeleted = false,
                            Name = "Intern",
                            NameEn = "Intern",
                            NameRu = "Стажер",
                            NameUz = "Stajyor",
                            Description = "A student or trainee who works in a company to gain work experience.",
                            DescriptionEn = "A student or trainee who works in a company to gain work experience.",
                            DescriptionRu = "Студент или стажер, который работает в компании для получения опыта работы.",
                            DescriptionUz = "Ish tajribasini olish uchun kompaniyada ishlovchi talaba yoki o'quvchi."
                        },
                        new
                        {
                            Id = new Guid("c70dcf80-ba5f-4a3e-9c32-2b56aec296d6"),
                            IsDeleted = false,
                            Name = "Full-time",
                            NameEn = "Full-time",
                            NameRu = "Полный рабочий день",
                            NameUz = "To'la vaqti",
                            Description = "Employee works a standard number of hours per week as defined by the employer.",
                            DescriptionEn = "Employee works a standard number of hours per week as defined by the employer.",
                            DescriptionRu = "Сотрудник работает стандартное количество часов в неделю, определенное работодателем.",
                            DescriptionUz = "Ishchi ish haftada ish joyi tomonidan belgilangan standart soatlar bo'yicha ishlaydi."
                        },
                        new
                        {
                            Id = new Guid("5980ce07-e74d-42e1-911c-bb8be7a6ecae"),
                            IsDeleted = false,
                            Name = "Part-time",
                            NameEn = "Part-time",
                            NameRu = "Неполный рабочий день",
                            NameUz = "Qisman ish",
                            Description = "Employee works fewer hours than a full-time employee.",
                            DescriptionEn = "Employee works fewer hours than a full-time employee.",
                            DescriptionRu = "Сотрудник работает меньше часов, чем на полный рабочий день.",
                            DescriptionUz = "Ishchi to'la vaqtli ishchidan kam soat ishlaydi."
                        },
                        new
                        {
                            Id = new Guid("5613ba01-5e26-48b4-a568-c18294cf940a"),
                            IsDeleted = false,
                            Name = "Remote",
                            NameEn = "Remote",
                            NameRu = "Удаленная работа",
                            NameUz = "Masofaviy",
                            Description = "Employee works from a location other than the office.",
                            DescriptionEn = "Employee works from a location other than the office.",
                            DescriptionRu = "Сотрудник работает не в офисе, а на удаленной основе.",
                            DescriptionUz = "Ishchi ofisdan boshqa joydan ishlaydi."
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserEducation", b =>
                {
                    b.HasOne("Domain.Entities.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserExperience", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WorkType", "WorkType")
                        .WithMany("UserExperience")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");

                    b.Navigation("User");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("Domain.Entities.UserLanguage", b =>
                {
                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserSocialNetwork", b =>
                {
                    b.HasOne("Domain.Entities.SocialNetwork", "SocialNetwork")
                        .WithMany()
                        .HasForeignKey("SocialNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialNetwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Education", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Educations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.HasOne("Domain.Entities.UserProject", null)
                        .WithMany("Skills")
                        .HasForeignKey("UserProjectId");
                });

            modelBuilder.Entity("Domain.Entities.UserCertificate", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserProject", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Educations");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Languages");

                    b.Navigation("Projects");

                    b.Navigation("Skills");

                    b.Navigation("SocialNetworks");
                });

            modelBuilder.Entity("Domain.Entities.UserProject", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Domain.Entities.WorkType", b =>
                {
                    b.Navigation("UserExperience");
                });
#pragma warning restore 612, 618
        }
    }
}
